name: Git action
description: Get basic details about the last commit

inputs:
  message-prefix:
    description: Prefix every log message with this message
    required: true

outputs:
  short-sha:
    description: Short SHA of the latest commit
    value: ${{ steps.commit-sha.outputs.sha }}
  commit-message:
    description: Full body of the latest commit
    value: ${{ steps.commit-message.outputs.message }}

runs:
  using: composite
  steps:
    - name: Get commit SHA
      id: commit-sha
      shell: bash
      env:
        MESSAGE_PREFIX: ${{ inputs.message-prefix }}
      run: |
        sha=$(git log -1 --pretty=format:"%h")
        echo "$MESSAGE_PREFIX: $sha"
        echo "sha=$sha" >> $GITHUB_OUTPUT
    - name: Get commit message
      id: commit-message
      shell: bash
      env:
        MESSAGE_PREFIX: ${{ inputs.message-prefix }}
      run: |
        message=$(git log -1 --pretty=format:"%s")
        echo "$MESSAGE_PREFIX: $message"
        echo "message=$message" >> $GITHUB_OUTPUT

