name: first workflow

on: 
  push: 
  workflow_dispatch:

jobs:
  simple-job:
    name: print details
    runs-on: ubuntu-latest
    steps:
      - name: print date
        run: echo `date`
                
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Print latest commit SHA
        run: |
          sha=$(git log -1 --pretty=format:"%h")
          echo "Short sha: $sha"

      - run: |
          message=$(git log -1 --pretty=format:"%B")
          echo "Last commit message: $message"

    