name: Build and deploy

on:
  workflow_dispatch:

env:
  IMAGE_NAME: myimageV1mufato

jobs:
  build:
    name: Build and push docker image
    runs-on: ubuntu-latest
    steps:
      - name: Check-out repo
        uses: actions/checkout@v4

      - name: Add a message
        working-directory: ./docker
        env:
          CUSTOM_MESSAGE: Very constant message
        run: |
          export MESSAGE="$CUSTOM_MESSAGE"
          envsubst < index-tmpl.html > index.html

      - name: Get commit info
        id: commit
        uses: ./.github/git
        with:
          message-prefix: Commit info

      - name: Build image
        working-directory: ./docker
        env:
          ARTIFACT_REGISTRY: europe-west1-docker.pkg.dev
          REPOSITORY_NAME: github-workshop-20231201/github-workshop
          IMAGE_TAG: ${{ steps.commit.outputs.short-sha }}
        run: docker build . -t $ARTIFACT_REGISTRY/$REPOSITORY_NAME/$IMAGE_NAME:$IMAGE_TAG

      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Configure docker
        env:
          ARTIFACT_REGISTRY: europe-west1-docker.pkg.dev
        run: gcloud auth configure-docker $ARTIFACT_REGISTRY

      - name: Push image to Artifact Registry
        env:
          ARTIFACT_REGISTRY: europe-west1-docker.pkg.dev
          REPOSITORY_NAME: github-workshop-20231201/github-workshop
          IMAGE_TAG: ${{ steps.commit.outputs.short-sha }}
        run: docker push $ARTIFACT_REGISTRY/$REPOSITORY_NAME/$IMAGE_NAME:$IMAGE_TAG

  deploy:
    name: Deploy to Cloud Run
    runs-on: ubuntu-latest
    needs: build
    env:
      SERVICE_NAME: mufato-service
    steps:
      - name: Check-out repo
        uses: actions/checkout@v4
    
      - name: Auth to Google Cloud
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_ACCOUNT }}

      - name: Deploy to Cloud Run
        env:
          ARTIFACT_REGISTRY: europe-west1-docker.pkg.dev
          REPOSITORY_NAME: github-workshop-20231201/github-workshop
          IMAGE_TAG: ${{ steps.commit.outputs.short-sha }}
        run: |
          gcloud run deploy $SERVICE_NAME \
            --image=$ARTIFACT_REGISTRY/$REPOSITORY_NAME/$IMAGE_NAME:$IMAGE_TAG \
            --region europe-west1 \
            --memory 256Mi \
            --cpu 200m \
            --min-instances 0 \
            --max-instances 1 \
            --port 80 \
            --timeout 10s \
            --allow-unauthenticated

      - name: Expose service
        run: |
          gcloud run services add-iam-policy-binding $SERVICE_NAME \
            --region europe-west1 \
            --member="allUsers" \
            --role="roles/run.invoker"

      - name: Get URL
        id: url
        run: |
          url=$(gcloud run services describe $SERVICE_NAME \
            --region europe-west1 \
            --format json \
            | jq -r ".status.address.url")
          echo "url=$url" >> $GITHUB_OUTPUT
      
      - name: Add summary
        env:
          SERVICE_URL: ${{ steps.url.outputs.url }}
        run: |
          echo "The image is deployed to serve on [URL]($SERVICE_URL)" >> $GITHUB_STEP_SUMMARY
